apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: secure-video
type: Opaque
stringData:
  mongodb-root-username: admin
  mongodb-root-password: securepassword123
  mongodb-database: secure-video